export const PROPRIEDADES_GERAIS = [
  { nome: "Ampla", desc: "Uma vez por rodada, escolha outro alvo adjacente. Se a defesa for menor que seu teste, recebe metade do dano." },
  { nome: "Aparar", desc: "Ação de movimento: +2 na Defesa até o próximo turno (se treinado)." },
  { nome: "Apunhaladora", desc: "+Treino de dano contra alvos desprevenidos." },
  { nome: "Arremessável", desc: "Pode ser usada em ataques de arremesso." },
  { nome: "Duas Mãos", desc: "Requer duas mãos para ser usada." },
  { nome: "Dupla", desc: "Pode ser usada para ataques adicionais (Estilo Duplo)." },
  { nome: "Emperrar", desc: "Em um 1 natural, a arma para de funcionar. Ação Comum para consertar." },
  { nome: "Enérgica", desc: "+1 dado de dano no segundo ataque do turno. Aumenta +1 a cada ataque extra." },
  { nome: "Especial", desc: "Possui um traço único." },
  { nome: "Estendida", desc: "+1,5m de alcance." },
  { nome: "Fatal", desc: "Crítico aumenta o dado para o tamanho listado e adiciona +1 dado extra se já for maior." },
  { nome: "Fineza", desc: "Pode usar Destreza no ataque e dano." },
  { nome: "Leve", desc: "Pode ser usada no manuseio de duas armas." },
  { nome: "Marcial", desc: "Beneficia-se de habilidades de Lutador." },
  { nome: "Modular", desc: "Pode causar um tipo de dano diferente (ex: Cortante)." },
  { nome: "Mortal", desc: "Crítico adiciona +1 dado de dano do tamanho listado." },
  { nome: "Oscilante", desc: "Se errar, recebe +2 no próximo ataque no mesmo turno." },
  { nome: "Pesada [X]", desc: "Requer Força X. Se não tiver, desvantagem no ataque." },
  { nome: "Recarga [X]", desc: "Após X ataques, gasta Ação Bônus para recarregar." },
  { nome: "Versátil", desc: "Pode usar com 1 ou 2 mãos (dano muda)." }
];

export const PROPRIEDADES_ESPECIAIS = [
  { nome: "Adagas Duplas", desc: "Ligadas. Não pode ser desarmado. Conta como arma de duas mãos." },
  { nome: "Alabarda", desc: "+2 em testes de Derrubar." },
  { nome: "Bazuca", desc: "Dano em área (7,5m do alvo). Recarga: Ação Completa. Munição Custo 1." },
  { nome: "Chakram", desc: "Retorna para a mão após arremesso." },
  { nome: "Chicote", desc: "Pode Agarrar com a arma ocupada (+2 no teste)." },
  { nome: "Chicote de Corrente", desc: "Pode enrolar em outra arma (Ação Bônus) para dar alcance e crítico do chicote para ela." },
  { nome: "Chicote Espinhento", desc: "Causa dano Cortante E Perfurante. Conta menor RD." },
  { nome: "Dardo", desc: "Se tiver veneno, CD aumenta em +2." },
  { nome: "Escopeta", desc: "Cone de 3m além do alvo. Recarga: Ação Comum." },
  { nome: "Espada de Gancho", desc: "Acerto puxa alvo 1,5m. Duas espadas ganham Estendida." },
  { nome: "Espada Colossal", desc: "Amplo afeta 2 criaturas adjacentes." },
  { nome: "Faixas", desc: "Conta como ataque desarmado. Pode ser encantada como arma." },
  { nome: "Kusarigama", desc: "Dano Cortante ou Impacto. +2 em Manobras." },
  { nome: "Leque", desc: "Fechado (Impacto/Bastão) ou Aberto (Cortante/Faca). +2 Fintar." },
  { nome: "Manoplas", desc: "Dano desarmado. Pode segurar itens. +1 nível de dano a cada 2 Força." },
  { nome: "Metralhadora", desc: "Ação Bônus: Ataque adicional (gasta munição). Recarga: Comum." },
  { nome: "Rede", desc: "Alvo fica Enredado (CD 20 escapar). 5 PV." },
  { nome: "Soco Inglês", desc: "Dano desarmado. Crítico de Faca. +1 CD Crítico a cada 2 For/Des." }
];

export const ENCANTAMENTOS_ARMAS = [
  { nome: "Afiada", desc: "Ganha Fatal d8 (ou aumenta nível). Requer Cortante/Perfurante." },
  { nome: "Amplificadora", desc: "Ataque aumenta dano do próximo Feitiço/Técnica em Metade Treino dados." },
  { nome: "Armazenadora", desc: "Armazena 5 PE em descanso longo. Pode recuperar empunhando." },
  { nome: "Balanceada", desc: "+2 em testes de manobras." },
  { nome: "Canalizadora", desc: "+2 na CD Amaldiçoada." },
  { nome: "Cano Alongado", desc: "+25% Alcance. (Apenas Distância)." },
  { nome: "Certeira", desc: "-1 Margem de Crítico. Incompatível com Destruidora." },
  { nome: "Compartimento", desc: "Armazena óleo/veneno. Aplica como Ação Livre." },
  { nome: "Complementar", desc: "+2 CD Especialização/Estilo." },
  { nome: "Cruel", desc: "+3 Dano." },
  { nome: "Defensora", desc: "Ganha Aparar (ou +1 se já tiver). (Apenas Corpo a Corpo)." },
  { nome: "Destruidora", desc: "+1 dado de dano no crítico." },
  { nome: "Discreta", desc: "+5 Furtividade para esconder a arma." },
  { nome: "Drenadora", desc: "Ao matar, recupera 2 PE por Grau da criatura." },
  { nome: "Elemental", desc: "Muda tipo de dano para Elemental. (Requer Grau 2)." },
  { nome: "Harmonizada", desc: "Crítico reduz custo da próxima habilidade em 1." },
  { nome: "Horrenda", desc: "Aumenta CD de efeitos de medo. (Requer outro encantamento)." },
  { nome: "Longa", desc: "+1,5m Alcance. (Apenas Corpo a Corpo)." },
  { nome: "Otimizada", desc: "Saque Livre. +2 Iniciativa." },
  { nome: "Penetrante", desc: "Ignora RD igual ao Treinamento." },
  { nome: "Poderosa", desc: "+2 Dano. (Requer Cruel)." },
  { nome: "Potente", desc: "+1 dado de dano. (Requer Grau 1)." },
  { nome: "Precisa", desc: "+2 Acerto." },
  { nome: "Reluzente", desc: "+2 Fintar. Crítico deixa Desprevenido/Cego (CD). -5 Furtividade." },
  { nome: "Retorno", desc: "Retorna à mão após arremesso." },
  { nome: "Sintonizada", desc: "Causar dano elemental com feitiço dá +1d8 dano elemental na arma. (Requer Grau 2)." }
];

export const ENCANTAMENTOS_ESCUDOS = [
  { nome: "Avassalador", desc: "Dano de ataque conta como 3 níveis acima. (Requer Destruidor)." },
  { nome: "Bloqueador", desc: "Concede Cobertura Leve para aliados atrás." },
  { nome: "Destruidor", desc: "Dano de ataque conta como 2 níveis acima. (Requer Espinhoso)." },
  { nome: "Disco", desc: "Ganha Arremesso 6/18. (Leve/Médio apenas)." },
  { nome: "Espinhoso", desc: "Dano de ataque conta como 1 nível acima." },
  { nome: "Esponja", desc: "Reação reduz dano de queda/colisão em 10 (15 Grau 2, 20 Grau 1)." },
  { nome: "Expansão de Escudo", desc: "Ação Bônus: Protege aliado adjacente também." },
  { nome: "Intangível", desc: "Não ocupa a mão para habilidades (mas não segura itens)." },
  { nome: "Isolante", desc: "RD do escudo aplica a um elemento escolhido." },
  { nome: "Polido", desc: "Reduz penalidade do escudo em 2." },
  { nome: "Reforçado", desc: "+2 RD Físico." }
];

export const ENCANTAMENTOS_UNIFORMES = [
  { nome: "Aeronauta", desc: "Reação ao cair: Plana, cai só 6m/turno." },
  { nome: "Ajustado", desc: "Reduz penalidade em 1. Se 0, +2 Furtividade." },
  { nome: "Blindado", desc: "+2 Defesa." },
  { nome: "Distorcivo", desc: "Cargas. Ação Livre: Teleporte 6m." },
  { nome: "Escaldante", desc: "Dano (Metade Treino d6) em quem agarrar (CD Fort)." },
  { nome: "Estimulante", desc: "Cargas. Reação: Vantagem em TR Fort/Ref/Von." },
  { nome: "Furtivo", desc: "+Custo em Furtividade." },
  { nome: "Impulso", desc: "Cargas. Movimento dobra em linha reta, dano em quem atravessar. (Requer Propulsor)." },
  { nome: "Isolante", desc: "5 RD Fogo/Gelo." },
  { nome: "Marcial", desc: "+2 Manobras." },
  { nome: "Material Pesado", desc: "+2 Fortitude. (Requer Médio/Robusto)." },
  { nome: "Propulsor", desc: "+3m Deslocamento." },
  { nome: "Repulsor", desc: "Cargas. Reação: Empurra 3m (CD Fort). (Requer Grau 2)." },
  { nome: "Resiliente", desc: "5 RD a um tipo (exceto físico/alma). 10 se Grau Especial." },
  { nome: "Revestido com Espinhos", desc: "Atacante corpo a corpo sofre dano (Treino d6 + Con) se falhar CD." },
  { nome: "Ricochete", desc: "20% chance falha projéteis. Carga (Reação): 50%." }
];
